debug: add circleci8

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,14 +25,15 @@ jobs:
       # mysql prepare
       - run:
         name: Waiting for MySQL to be ready
-        command: |
-          for i in `seq 1 10`;
-          do
-            nc -z 127.0.0.1 3306 && echo Success && exit 0
-            echo -n .
-            sleep 1
-          done
-          echo Failed waiting for MySQL && exit 1
+        command: dockerize -wait tcp://localhost:3306 -timeout 1m
+#        command: |
+#          for i in `seq 1 10`;
+#          do
+#            nc -z 127.0.0.1 3306 && echo Success && exit 0
+#            echo -n .
+#            sleep 1
+#          done
+#          echo Failed waiting for MySQL && exit 1
 
       # go run test
       - run: go test -race
